add mc tweak disableHoneyBlockEffect
Fallen-Breath/tweakermore pull request #74
Opened 2024-08-18 22:38 UTC by topi-banana

2024-08-30 09:55 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tweakermore/mixins/tweaks/mc_tweaks/disableHoneyBlockEffect/HoneyBlockMixin.java
> +  @Inject(method = "onEntityCollision", at = @At("HEAD"), cancellable = true)
Suggestion: apply `@ModifiyExpressionValue` onto the `isSliding` call. Much better than inject + cancel

2024-08-30 10:00 UTC, Fallen-Breath requested changes
- Please keep the coding style, i.e. tab + brace-on-new-line on all files
- Please maintain the config name / description in the language file (at least for en_us)

2024-09-02 07:28 UTC, topi-banana commented
thank you for your review.
I've made the necessary changes.

2024-09-02 07:35 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tweakermore/mixins/tweaks/mc_tweaks/disableHoneyBlockEffect/HoneyBlockMixin.java
> +  @ModifyExpressionValue(
code styling

2024-09-02 07:38 UTC, topi-banana commented on src/main/java/me/fallenbreath/tweakermore/mixins/tweaks/mc_tweaks/disableHoneyBlockEffect/HoneyBlockMixin.java
> +  @ModifyExpressionValue(
Uh, indent space -> tab?

2024-09-02 07:44 UTC, topi-banana commented
Is this okay?

2024-09-03 15:51 UTC, Fallen-Breath approved these changes
LGTM

2024-09-03 15:51 UTC, merged